[package]
name = "graph-http"
version = "0.2.2"
authors = ["sreeise"]
edition = "2021"
license = "MIT"
repository = "https://github.com/sreeise/graph-rs"
description = "Http client and utilities for the graph-rs project"

[dependencies]
async-std = "1.6.0"
async-stream = "0.3"
async-trait = "0.1.35"
bytes = "1"
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
handlebars = "2.0.2"
parking_lot = "0.12.0"
percent-encoding = "2"
reqwest = { version = "0.11", features = ["json", "blocking", "stream", "multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
url = { version = "2", features = ["serde"] }

graph-error = { path = "../graph-error"  }
graph-core = { path = "../graph-core" }
